site_name: Deep Space Capabilities
site_url: https://lukeyjohnson.github.io/bg-sites/
repo_url: https://github.com/lukeyjohnson/bg-sites/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
  palette: 
    scheme: default
    primary: indigo
    accent: blue

nav:
  - Home: index.md
  - Capabilities:
      - DS Pro (Technical): index.md#ds-pro
      - DS Harmony (Field): index.md#ds-harmony
      - DS Horizon (Ops): index.md#ds-horizon
  - Site and Mobile: siteapp.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences